### ISSUE TITLE
validator error: Layer 'Postprocessor/scale_logits:0' consumes an input named 'concat__0' which is not present in this network.

### ISSUE THREAD

**Issue by Shelro** [hollance/coreml-survival-guide#4]
Hi hollance!
Really thank you for your blogs about coreML.

Here is the thing. So I trained a Mobilenetv2+SSDlite model for my own data with 2 classes, and I used ssdlite_mobilenet_v2_coco just like you. When I tried to convert my model to coreML model using your script, I get several errors like below:

1.  `Traceback (most recent call last):  
    File "ssdlite.py", line 142, in <module>
        del spec.description.output[1].type.multiArrayType.shape[-1]
IndexError: List assignment index out of range`
So I check spec.description, and I get a result like this:

> output{
>   name: "scores"
>   shortDescription: "Predicted class scores for each bounding box"
>   type {
>     multiArrayType {
>       shape: 3
>       shape: 1917
>       dataType: DOUBLE
>     }
>   }
> }
> output{
>   name: "boxes"
>   shortDescription: "Predicted coordinates for each bounding box"
>   type {
>     multiArrayType {
>       dataType: DOUBLE
>     }
>   }
> }

Which means, somehow, the output shape of the "boxes" output is not filled in. And I notices you added the output shape of the "scores" output, so I did the same way and convert coreML model successfully. Then I got another error.

2.  `validator error: Layer 'Postprocessor/scale_logits:0' consumes an input named 'concat__0' which is not present in this network.`
When I got the final coreML model and add it to xcode project, I found it got an error as shown above. The screen shot of it is added in below.
<img width="731" alt="2019-02-28 9 00 49" src="https://user-images.githubusercontent.com/17904714/53568160-3f08f780-3b9c-11e9-9a2a-1dc5db073fc0.png">

I used coremltools 2.0, tfcoreml 0.3.0, tensorflow1.10.0(I was trained in this version, so had to convert it in this tensorflow version) and python 3.6.5 . I only changed the number of classes, if you know anything about this, please tell me. Thank you very much!

**Comment by hollance** [comment]
It seems that your model has a few different operations — or the same operations but with different names — than the conversion script expects.

**Comment by Shelro** [comment]
Hi, I am happy to receive your respond, and I am glad to tell you that I solved this problem.
After reading https://github.com/tf-coreml/tf-coreml/blob/master/examples/ssd_example.ipynb , I did some modification like below:
Before: `bbox_output_node = "concat"`
After: `bbox_output_node = "concat_1"`

And it works well on my iPhone.
Hope this information can help others.

Thank you again for your work.
