### ISSUE TITLE
Output node for handtracking model

### ISSUE THREAD

**Issue by baptadn** [hollance/coreml-survival-guide#5]
Hello 👋 Thanks for [your post](https://machinethink.net/blog/mobilenet-ssdlite-coreml/) about converting MobileNetV2_SSDLite to coreml model.

I try to convert [this model (hand detection)](https://github.com/victordibia/handtracking/tree/master/model-checkpoint/ssdlitemobilenetv2) to coreML, but I'm struggling to find the right [bbox output node](https://github.com/hollance/coreml-survival-guide/blob/master/MobileNetV2%2BSSDLite/ssdlite.py#L67) (even with Netron). Do you have any advices for me ?

Thanks again :)

**Comment by hollance** [comment]
I don’t have time to look right now but the file you should look at is frozen_inference_model.pb and it’s usually near the bottom somewhere in Netron.

**Comment by baptadn** [comment]
Thanks :)
