### ISSUE TITLE
VNCoreMLTransformer

### ISSUE THREAD

**Issue by tsingjinyun** [hollance/coreml-survival-guide#9]
Error Domain=com.apple.vis Code=3 "Failed to initialize VNCoreMLTransformer" UserInfo={NSLocalizedDescription=Failed to initialize VNCoreMLTransformer, NSUnderlyingError=0x1d0a455b0 {Error Domain=com.apple.vis Code=5 "No valid VNCoreMLModel found in passed in options" UserInfo={NSLocalizedDescription=No valid VNCoreMLModel found in passed in options}}}	

 ----------------
@hollance ,hello ,have you come over this error?

**Comment by hollance** [comment]
What kind of model are you using where you're getting this error?

One situation where I can imagine getting this error is when the model does not have an image input, or it has additional inputs that do not have default values.

**Comment by tsingjinyun** [comment]
@hollance ,thanks for your advice, i have convert caffemodel of SSD to coreml, the error is input must match image or multiarray.  After check the code input,  and solve this problem. thanks again for you advice.
